// pages/alipan-tv-token/index.vue
<template>
  <head>
        <title>与「阿里云盘」连接</title>
    </head>
  <div class="p-4">
    <!-- 主体部分 -->
    <div class="mx-auto w-full max-w-3xl bg-white shadow-lg rounded-lg p-8 mb-8">
      <div class="flex justify-between items-center mb-6">
        <h1 class="text-2xl font-bold text-gray-800">与「阿里云盘」连接</h1>
      </div>

      <div class="space-y-8">
        <div class="space-y-2">
          <div class="relative">
            <a-textarea :rows="5" id="accessToken" :value="accessToken"
              class="w-full rounded font-mono text-sm leading-normal border-2 border-dashed border-gray-300 p-3 pr-10 bg-white resize-none focus:outline-none focus:border-blue-500 transition-colors min-h-[120px] whitespace-pre-wrap overflow-auto placeholder:text-gray-400"
              readonly spellcheck="false" placeholder="访问令牌" />
            <button data-clipboard-target="#accessToken" :class="`absolute top-2 right-2 p-1 rounded transition-colors ${hasAccessToken
              ? 'hover:bg-gray-100 text-gray-500 hover:text-blue-500'
              : 'text-gray-300 cursor-not-allowed'
              }`" :disabled="!hasAccessToken">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
              </svg>
            </button>
          </div>
        </div>

        <div class="space-y-2">
          <div class="relative">
            <a-textarea :rows="4" id="refreshToken" :value="refreshToken"
              class="w-full rounded font-mono text-sm leading-normal border-2 border-dashed border-gray-300 p-3 pr-10 bg-white resize-none focus:outline-none focus:border-blue-500 transition-colors min-h-[120px] whitespace-pre-wrap overflow-auto placeholder:text-gray-400"
              readonly spellcheck="false" placeholder="刷新令牌" />
            <button data-clipboard-target="#refreshToken" :class="`absolute top-2 right-2 p-1 rounded transition-colors ${hasRefreshToken
              ? 'hover:bg-gray-100 text-gray-500 hover:text-blue-500'
              : 'text-gray-300 cursor-not-allowed'
              }`" :disabled="!hasRefreshToken">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
              </svg>
            </button>
          </div>
        </div>

        <div id="authSection" class="h-[52px]">
          <div v-if="isLoading" class="flex justify-center items-center h-full">
            <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-500"></div>
            <span class="ml-3 text-gray-600">正在获取授权链接...</span>
          </div>
          <button v-else @click="handleAuth(authUrl)" :disabled="authorizing" :class="`block w-full bg-blue-500 text-white text-center py-3 px-4 rounded transition-colors relative ${authorizing ? 'bg-blue-400 cursor-not-allowed' : 'hover:bg-blue-600'
            }`">
            <div class="flex items-center justify-center">
              <div v-if="authorizing"
                class="animate-spin rounded-full h-5 w-5 border-2 border-white border-t-transparent mr-2"></div>
              <svg v-else xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24"
                stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1" />
              </svg>
              {{ authorizing ? '授权中...' : '授权登录' }}
            </div>
          </button>
        </div>
      </div>
    </div>

    <!-- 文档部分 -->
    <div class="mx-auto w-full max-w-3xl bg-white shadow-lg rounded-lg p-8">
      <div class="prose prose-sm max-w-none">
        <h2 class="text-xl font-bold mb-4">使用说明</h2>
        <h3 class="text-lg font-semibold mt-6 mb-2">路由:</h3>
        <ul class="list-disc pl-5 mb-4">
          <li><code class="bg-gray-100 px-1 rounded">/api/oauth/alipan/token⁠</code> 刷新令牌</li>
        </ul>
        <h3 class="text-lg font-semibold mt-6 mb-2">在 alist 中配置 alipan-tv-token 的地址</h3>
        <p>在 alist 的阿里云盘open配置中：</p>
        <ul class="list-disc pl-5">
          <li>Oauth令牌链接填写: <code
              class="bg-gray-100 px-1 rounded">http://alipan-tv-token:3000/api/oauth/alipan/token⁠</code></li>
          <li>如果需要获取 token，访问: <code class="bg-gray-100 px-1 rounded">http://你的IP:3000/alipan-tv-token</code></li>
        </ul>
      </div>
    </div>
  </div>
  <a-modal v-model:open="isNoticeOpen" title="使用说明" @ok="closeNotice" :maskClosable="false" :closable="false"
    :keyboard="false">
    <p>本工具能帮助你一键获取「阿里云盘TV版」的刷新令牌，完全免费。TV接口能绕过三方应用权益包的速率限制，但前提你得是SVIP。</p>
    <template #footer>
      <!-- 开通会员链接 -->
      <a-button type="primary" danger href="https://www.alipan.com/cpx/member?userCode=MjAyNTk2" target="_blank">开通会员</a-button>
      <a-button type="primary" @click="closeNotice">我知道了</a-button>
    </template>
  </a-modal>
</template>

<script setup>
import { ref, onMounted, onUnmounted } from 'vue'
import { message } from 'ant-design-vue'
import ClipboardJS from 'clipboard'

const hasGenerated = ref(false)
const authUrl = ref('')
const isLoading = ref(true)
const hasAccessToken = ref(false)
const hasRefreshToken = ref(false)
const authorizing = ref(false)
const isNoticeOpen = ref(false)
const accessToken = ref('')
const refreshToken = ref('')

const checkTimer = ref(null)
const isComponentMounted = ref(true)

async function generateAuthUrl() {
  try {
    isLoading.value = true
    const data = await $fetch("/api/alipan-tv-token/generate_qr", { method: "POST" })
    authUrl.value = `https://www.alipan.com/o/oauth/authorize?sid=${data.sid}`
    checkStatus(data.sid)
  } finally {
    isLoading.value = false
  }
}

function closeNotice() {
  isNoticeOpen.value = false
}

async function checkStatus(sid) {
  if (!isComponentMounted.value) return
  
  try {
    const data = await $fetch("/api/alipan-tv-token/check_status/" + sid)
    if (data.status === "LoginSuccess") {
      accessToken.value = data.access_token
      refreshToken.value = data.refresh_token
      document.getElementById("authSection").style.visibility = "hidden"
      hasAccessToken.value = !!data.access_token
      hasRefreshToken.value = !!data.refresh_token
      message.success('登录成功')
      initializeClipboard() // 在 token 设置后初始化 ClipboardJS
    } else if (data.status === "ScanSuccess" && isComponentMounted.value) {
      checkTimer.value = setTimeout(() => checkStatus(sid), 2000)
    } else if (data.status === "LoginFailed") {
      message.error('登录失败，请刷新页面重试')
    } else if (data.status === "QRCodeExpired") {
      message.error('链接过期，请刷新页面重试')
    } else if (isComponentMounted.value) {
      checkTimer.value = setTimeout(() => checkStatus(sid), 2000)
    }
  } catch (error) {
    console.error("检查状态时出错：", error)
    message.error('发生错误，请稍后重试')
  }
}

// 初始化 ClipboardJS
function initializeClipboard() {
  const accessTokenClipboard = new ClipboardJS('[data-clipboard-target="#accessToken"]')
  accessTokenClipboard.on('success', () => {
    message.success('已复制访问令牌')
  })
  accessTokenClipboard.on('error', () => {
    message.error('复制失败')
  })

  const refreshTokenClipboard = new ClipboardJS('[data-clipboard-target="#refreshToken"]')
  refreshTokenClipboard.on('success', () => {
    message.success('已复制刷新令牌')
  })
  refreshTokenClipboard.on('error', () => {
    message.error('复制失败')
  })
}

const handleAuth = (url) => {
  authorizing.value = true
  window.open(url, '_blank')
}

onMounted(() => {
  // 先显示弹框
  isNoticeOpen.value = true
  if (!hasGenerated.value) {
    generateAuthUrl()
    hasGenerated.value = true
  }
})
onUnmounted(() => {
  isComponentMounted.value = false
  if (checkTimer.value) {
    clearTimeout(checkTimer.value)
  }
})

</script>

<style scoped></style>

// app/alipan-tv-token/page.tsx
"use client";

import { useState, useEffect, useRef } from "react";
import { 
  Input, 
  Modal, 
  Button, 
  message, 
  Card, 
  Typography, 
  Space, 
  Row, 
  Col,
  Flex,
  Spin,
  Alert
} from "antd";
import {
  CopyOutlined,
  LoadingOutlined,
  LoginOutlined,
  ApiOutlined,
  SettingOutlined,
  BulbOutlined,
  BookOutlined
} from "@ant-design/icons";
import ClipboardJS from "clipboard";
import Head from "next/head";

const { TextArea } = Input;
const { Title, Paragraph } = Typography;

export default function AlipanTvToken() {
  const [hasGenerated, setHasGenerated] = useState(false);
  const [authUrl, setAuthUrl] = useState("");
  const [isLoading, setIsLoading] = useState(true);
  const [hasAccessToken, setHasAccessToken] = useState(false);
  const [hasRefreshToken, setHasRefreshToken] = useState(false);
  const [authorizing, setAuthorizing] = useState(false);
  const [isNoticeOpen, setIsNoticeOpen] = useState(false);
  const [accessToken, setAccessToken] = useState("");
  const [refreshToken, setRefreshToken] = useState("");
  const [currentSid, setCurrentSid] = useState("");

  const checkTimer = useRef<NodeJS.Timeout | null>(null);
  async function generateAuthUrl() {
    try {
      setIsLoading(true);
      const response = await fetch("/api/alipan-tv-token/generate_qr", {
        method: "POST",
      });
      const data = await response.json();
      setCurrentSid(data.sid);
      setAuthUrl(`https://www.alipan.com/o/oauth/authorize?sid=${data.sid}`);
    } finally {
      setIsLoading(false);
    }
  }

  function closeNotice() {
    setIsNoticeOpen(false);
  }

  async function checkStatus(sid: string) {
    console.log("Checking status for SID:", sid);

    try {
      const response = await fetch(`/api/alipan-tv-token/check_status/${sid}`);
      const data = await response.json();
      if (data.status === "LoginSuccess") {
        setAccessToken(data.access_token);
        setRefreshToken(data.refresh_token);
        const authSection = document.getElementById("authSection");
        if (authSection) {
          authSection.style.visibility = "hidden";
        }
        setHasAccessToken(!!data.access_token);
        setHasRefreshToken(!!data.refresh_token);
        setAuthorizing(false);
        message.success("登录成功");
        initializeClipboard();
      } else if (data.status === "ScanSuccess") {
        checkTimer.current = setTimeout(() => checkStatus(sid), 2000);
      } else if (data.status === "LoginFailed") {
        setAuthorizing(false);
        message.error("登录失败，请刷新页面重试");
      } else if (data.status === "QRCodeExpired") {
        setAuthorizing(false);
        message.error("链接过期，请刷新页面重试");
      } else {
        checkTimer.current = setTimeout(() => checkStatus(sid), 2000);
      }
    } catch (error) {
      console.error("检查状态时出错：", error);
      message.error("发生错误，请稍后重试");
    }
  }

  function initializeClipboard() {
    const accessTokenClipboard = new ClipboardJS(
      '[data-clipboard-target="#accessToken"]'
    );
    accessTokenClipboard.on("success", () => {
      message.success("已复制访问令牌");
    });
    accessTokenClipboard.on("error", () => {
      message.error("复制失败");
    });

    const refreshTokenClipboard = new ClipboardJS(
      '[data-clipboard-target="#refreshToken"]'
    );
    refreshTokenClipboard.on("success", () => {
      message.success("已复制刷新令牌");
    });
    refreshTokenClipboard.on("error", () => {
      message.error("复制失败");
    });
  }
  const handleAuth = (url: string) => {
    setAuthorizing(true);
    window.open(url, "_blank");

    // 重新启动状态检查
    if (currentSid) {
      // 清除之前的定时器
      if (checkTimer.current) {
        clearTimeout(checkTimer.current);
      }
      // 延迟一秒后开始检查状态，给用户一些时间进行授权
      checkTimer.current = setTimeout(() => checkStatus(currentSid), 1000);
    }
  };

  useEffect(() => {
    setIsNoticeOpen(true);
    if (!hasGenerated) {
      generateAuthUrl();
      setHasGenerated(true);
    }

    return () => {
      if (checkTimer.current) {
        clearTimeout(checkTimer.current);
      }
    };
  }, [hasGenerated]);  return (
    <>
      <Head>
        <title>阿里云盘TV授权 - 爱拓工具箱</title>
      </Head>
      
      <Space direction="vertical" size="large" style={{ width: "100%" }}>
        {/* 页面标题 */}
        <Card>
          <Flex vertical align="center" gap="small">
            <Typography.Title level={1} className="gradient-text" style={{ margin: 0 }}>
              🎬 阿里云盘TV授权
            </Typography.Title>
            <Typography.Text type="secondary" style={{ fontSize: 16, textAlign: "center" }}>
              获取阿里云盘TV端的授权令牌，解锁高速下载
            </Typography.Text>
          </Flex>
        </Card>

        {/* 主功能区域 */}
        <Row gutter={[24, 24]}>
          <Col xs={24} lg={12}>
            <Space direction="vertical" size="large" style={{ width: "100%" }}>
              {/* 访问令牌 */}
              <Card 
                title={
                  <Space>
                    <CopyOutlined />
                    <span>访问令牌</span>
                  </Space>
                } 
                size="small"
                extra={
                  <Button
                    data-clipboard-target="#accessToken"
                    type="text"
                    icon={<CopyOutlined />}
                    disabled={!hasAccessToken}
                    size="small"
                  />
                }
              >
                <Input.TextArea
                  id="accessToken"
                  value={accessToken}
                  readOnly
                  rows={4}
                  placeholder="授权成功后，访问令牌将显示在这里..."
                />
              </Card>

              {/* 刷新令牌 */}
              <Card 
                title={
                  <Space>
                    <span>🔄</span>
                    <span>刷新令牌</span>
                  </Space>
                } 
                size="small"
                extra={
                  <Button
                    data-clipboard-target="#refreshToken"
                    type="text"
                    icon={<CopyOutlined />}
                    disabled={!hasRefreshToken}
                    size="small"
                  />
                }
              >
                <Input.TextArea
                  id="refreshToken"
                  value={refreshToken}
                  readOnly
                  rows={3}
                  placeholder="刷新令牌将显示在这里..."
                />
              </Card>
            </Space>
          </Col>

          <Col xs={24} lg={12}>
            {/* 授权操作 */}
            <Card 
              title={
                <Space>
                  <LoginOutlined />
                  <span>授权操作</span>
                </Space>
              }
            >
              <div id="authSection">
                {isLoading ? (
                  <Flex vertical align="center" gap="middle">
                    <Spin size="large" />
                    <Typography.Text type="secondary">
                      正在获取授权链接...
                    </Typography.Text>
                  </Flex>
                ) : (
                  <Button
                    type="primary"
                    size="large"
                    block
                    onClick={() => handleAuth(authUrl)}
                    disabled={authorizing}
                    icon={authorizing ? <LoadingOutlined /> : <LoginOutlined />}
                  >
                    {authorizing ? "授权中..." : "开始授权登录"}
                  </Button>
                )}
              </div>
            </Card>
          </Col>
        </Row>

        {/* 使用说明 */}
        <Card 
          title={
            <Space>
              <BookOutlined />
              <span>使用说明</span>
            </Space>
          }
        >
          <Space direction="vertical" size="large" style={{ width: "100%" }}>
            <Row gutter={[24, 24]}>
              <Col xs={24} md={8}>
                <Card 
                  title={
                    <Space>
                      <ApiOutlined />
                      <span>API路由</span>
                    </Space>
                  } 
                  size="small"
                >
                  <Typography.Paragraph>
                    <Typography.Text code>/api/oauth/alipan/token</Typography.Text>
                    <br />
                    刷新令牌接口
                  </Typography.Paragraph>
                </Card>
              </Col>

              <Col xs={24} md={8}>
                <Card 
                  title={
                    <Space>
                      <SettingOutlined />
                      <span>Alist 配置</span>
                    </Space>
                  } 
                  size="small"
                >
                  <Space direction="vertical" size="small" style={{ width: "100%" }}>
                    <Typography.Paragraph>
                      <Typography.Text strong>Oauth令牌链接：</Typography.Text>
                      <br />
                      <Typography.Text code>
                        http://alipan-tv-token:3000/api/oauth/alipan/token
                      </Typography.Text>
                    </Typography.Paragraph>
                    <Typography.Paragraph>
                      <Typography.Text strong>获取令牌访问：</Typography.Text>
                      <br />
                      <Typography.Text code>
                        http://你的IP:3000/alipan-tv-token
                      </Typography.Text>
                    </Typography.Paragraph>
                  </Space>
                </Card>
              </Col>

              <Col xs={24} md={8}>
                <Card 
                  title={
                    <Space>
                      <BulbOutlined />
                      <span>温馨提示</span>
                    </Space>
                  } 
                  size="small"
                >
                  <Alert
                    message="TV接口能绕过三方应用权益包的速率限制，但需要SVIP会员才能享受高速下载。"
                    type="warning"
                    showIcon
                  />
                </Card>
              </Col>
            </Row>
          </Space>
        </Card>
      </Space>

      <Modal
        open={isNoticeOpen}
        title="使用说明"
        onOk={closeNotice}
        maskClosable={false}
        closable={false}
        keyboard={false}
        footer={[
          <Button
            key="member"
            type="primary"
            danger
            href="https://www.alipan.com/cpx/member?userCode=MjAyNTk2"
            target="_blank"
          >
            开通会员
          </Button>,
          <Button key="ok" type="primary" onClick={closeNotice}>
            我知道了
          </Button>,
        ]}
      >
        <Typography.Paragraph>
          本工具能帮助你一键获取「阿里云盘TV版」的刷新令牌，完全免费。TV接口能绕过三方应用权益包的速率限制，但前提你得是SVIP。
        </Typography.Paragraph>
      </Modal>
    </>
  );
}
